#
# Cookbook Name:: resolvconf
# Attribute:: default
#
# Copyright 2012, Chris Aumann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

default['resolvconf']['head'] = [
  '# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)',
  '#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN'
]

default['resolvconf']['base'] = []
default['resolvconf']['tail'] = []

# shortcuts for specify /etc/resolv.conf options (will be added to node['resolvconf']['base'])
default['resolvconf']['nameserver'] = [ '208.67.222.222', '208.67.220.220' ] # OpenDNS
default['resolvconf']['search'] = node['domain']
default['resolvconf']['options'] = []

# removes all dns-* entries from /etc/network/interfaces if true
default['resolvconf']['clear-dns-from-interfaces'] = true
